services:
  backend:
    build:
      dockerfile: Dockerfile
      context: /java
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/travel?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile
      context: /frontend
    ports:
      - 3000:3000
    restart: always
    env_file:
      - /frontend/.env

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: travel
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    restart: always
